### PR TITLE
Fix another flakiness in the test

### PR DESCRIPTION
**Pull request by raeeschachar**

### CODE REVIEW

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
@benpatterson @jzoldak @Muddasser 
Please review. Fixes the flakiness of the following:
test_cancel_upload 
test_logout

**Comment by benpatterson** [comment]
jenkins run e2e

**Comment by benpatterson** [comment]
The change makes sense; however the last build did not complete. Have they been aborting all along?

**Comment by raeeschachar** [comment]
@benpatterson I manually aborted that one to rerun for testing :)

**Comment by raeeschachar** [comment]
jenkins run e2e

**Pull request merged**
