### PR TITLE
Revert "EDUCATOR-2335: Remove flaky test_assignment_types test."

### PR DESCRIPTION
**Pull request by awaisdar001**
Reverts edx/edx-e2e-tests#252

Timing out issue is addressed in https://openedx.atlassian.net/browse/WL-1435.
Adding tests back.

### CODE REVIEW

**Comment by awaisdar001** [comment]
Adding `flaky` decorator.

**Comment by awaisdar001** [comment]
jenkins run e2e

**Comment by awaisdar001** [comment]
@robrap Do you think I need to keep `flaky` in place as it is required sometimes? Need your thoughts?

**Comment by robrap** [comment]
@awaisdar001: I would not leave it unused.  You could update the [Flaky Test Process page](https://openedx.atlassian.net/wiki/spaces/TE/pages/161427235/Flaky+Test+Process) to mention how to do what you did.  We don't want flaky decorators committed by mistake, and I don't want the dependency to make someone feel like it is ok to commit code with the decorator.
Thank you!

**Comment by awaisdar001** [comment]
@robrap removed the `flaky` decorator.

**Pull request merged**
