### PR TITLE
Fix and improve install process

### PR DESCRIPTION
**Pull request by laurentdavid**
- Fix vagrant provision process so to install all dependencies
- Add a sample local_env file to setup environment variables

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @laurentdavid! I've created [OSPR-1607](https://openedx.atlassian.net/browse/OSPR-1607) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-e2e-tests/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by jzoldak** [comment]
@laurentdavid - apologies that this PR seems to have slipped through the cracks. 😞  I've just noticed it now while submitting #109.

I'm thinking that the most expedient way to get your changes merged in will be for me to pull your commit into my branch, resolve the conflicts, and review/merge together. I'll get that rolling now.

**Comment by jzoldak** [comment]
Closing, pulling changeset into #109

**Comment by jzoldak** [comment]
@laurentdavid Your changes have been merged into master. Thanks for your contribution!

**Pull request closed without merging**
