### PR TITLE
Paver commands for whitelabel tests

### PR DESCRIPTION
**Pull request by Muddasser**

### CODE REVIEW

**Comment by Muddasser** [comment]
jenkins run microsites

**Comment by Muddasser** [comment]
jenkins run microsites

**Comment by Muddasser** [comment]
@raeeschachar @jzoldak Tests are failing but it is a genuine issue from the backend of whitelabel tests. Failures are not related to changes in this PR.

**Comment by raeeschachar** [comment]
jenkins run microsites

**Comment by raeeschachar** [comment]
jenkins run microsites

**Comment by raeeschachar** [comment]
@edx/testeng 
I am going to merge this ticket as this is approved and the failures are not related to this change. I will be creating another PR for the fix of the failing tests. It is related to https://openedx.atlassian.net/browse/WL-1058 fyi

**Pull request merged**
