### PR TITLE
Move page object for grading upstream

### PR DESCRIPTION
**Pull request by raeeschachar**

### CODE REVIEW

**Comment by raeeschachar** [comment]
@jzoldak 
I am not sure if I was able to understand https://openedx.atlassian.net/browse/LT-54 completely. I have created this PR till my understanding. Please review and let me know if there is anything else that you were expecting too.

**Comment by raeeschachar** [comment]
@benpatterson @jzoldak @Muddasser 
Reminder: Review?

**Comment by jzoldak** [comment]
@raeeschachar Sorry, I was unclear. :( 

I was thinking that what we should do is to move these improvements out of the utils and GradingExtended Page of this repo, upstream to where other tests (including the bok-choy tests in the edx-platform repo itself) can take advantage of them.

* I would look to put the utils stuff somewhere such as [acceptance/pages/studio/utils.py](https://github.com/edx/edx-platform/blob/master/common/test/acceptance/pages/studio/utils.py)
* and the generic GradingPage methods in [acceptance/pages/studio/settings_graders.py](https://github.com/edx/edx-platform/blob/master/common/test/acceptance/pages/studio/settings_graders.py)

Once we get the save_changes_popup_for_studio method over there, we should be able to improve other page objects in edx-platform to use it, where/if it makes sense to do so.

**Comment by jzoldak** [comment]
@raeeschachar Sorry, I was unclear. :( 

I was thinking that what we should do is to move these improvements out of the utils and GradingExtended Page of this repo, upstream to the edx-platform repo to where other tests (including the bok-choy tests in the edx-platform repo itself) can take advantage of them.

It'll be 2 PRs, the first adding the stuff over there, and the 2nds removing from here (referencing there).

* I would look to put the utils stuff somewhere such as [acceptance/pages/studio/utils.py](https://github.com/edx/edx-platform/blob/master/common/test/acceptance/pages/studio/utils.py)
* and the generic GradingPage methods in [acceptance/pages/studio/settings_graders.py](https://github.com/edx/edx-platform/blob/master/common/test/acceptance/pages/studio/settings_graders.py)

Once we get the save_changes_popup_for_studio method over there, we should be able to improve other page objects in edx-platform to use it, where/if it makes sense to do so.

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
@benpatterson @estute @Muddasser 
Please review.

**Comment by estute** [comment]
jenkins run e2e

**Comment by estute** [comment]
Reran after https://github.com/edx/edx-platform/pull/14558 was deployed

**Comment by estute** [comment]
:+1: Looks good. Ran a few times on Jenkins and locally (once the corresponding changes on platform were deployed to stage) and the flaky failures were not a result of these changes.

**Pull request merged**
