### PR TITLE
[BD-18] switch from nose to pytest

### PR DESCRIPTION
**Pull request by emzubair**
## switch from nose to pytest
updated paver commands

**Packages Removed**

- nose

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @emzubair! I've created [BLENDED-424](https://openedx.atlassian.net/browse/BLENDED-424) to keep track of it in Jira.  More details are on the [BD-18](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1593934815/BD-18+Testing+Consistency+Improvements) project page.

When this pull request is ready, tag your edX technical lead.

**Comment by feanil** [comment]
jenkins run e2e

**Comment by feanil** [comment]
jenkins run e2e

**Comment by feanil** [comment]
@emzubair Looks like the new scripts fail to run:
```
00:01:21.229 SCREENSHOT_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' SELENIUM_DRIVER_LOG_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' pytest /home/jenkins/workspace/****-e2e-tests-pr/regression/tests -v --junit-xml='/home/jenkins/workspace/****-e2e-tests-pr/reports/e2e_tests_results.xml' --exclude=whitelabel\|enterprise
00:01:21.519 ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
00:01:21.519 pytest: error: unrecognized arguments: --exclude=whitelabel|enterprise
00:01:21.519   inifile: None
00:01:21.519   rootdir: /home/jenkins/workspace/****-e2e-tests-pr
00:01:21.520 
00:01:21.551 
00:01:21.551 
00:01:21.551 Captured Task Output:
00:01:21.551 ---------------------
00:01:21.552 
00:01:21.552 ---> pavement.e2e_test
00:01:21.552 ---> pavement.configure_e2e_tests_pre_reqs
00:01:21.552 SCREENSHOT_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' SELENIUM_DRIVER_LOG_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' pytest /home/jenkins/workspace/****-e2e-tests-pr/regression/tests -v --junit-xml='/home/jenkins/workspace/****-e2e-tests-pr/reports/e2e_tests_results.xml' --exclude=whitelabel\|enterprise
```

**Comment by emzubair** [comment]
> @emzubair Looks like the new scripts fail to run:
> 
> ```
> 00:01:21.229 SCREENSHOT_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' SELENIUM_DRIVER_LOG_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' pytest /home/jenkins/workspace/****-e2e-tests-pr/regression/tests -v --junit-xml='/home/jenkins/workspace/****-e2e-tests-pr/reports/e2e_tests_results.xml' --exclude=whitelabel\|enterprise
> 00:01:21.519 ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> 00:01:21.519 pytest: error: unrecognized arguments: --exclude=whitelabel|enterprise
> 00:01:21.519   inifile: None
> 00:01:21.519   rootdir: /home/jenkins/workspace/****-e2e-tests-pr
> 00:01:21.520 
> 00:01:21.551 
> 00:01:21.551 
> 00:01:21.551 Captured Task Output:
> 00:01:21.551 ---------------------
> 00:01:21.552 
> 00:01:21.552 ---> pavement.e2e_test
> 00:01:21.552 ---> pavement.configure_e2e_tests_pre_reqs
> 00:01:21.552 SCREENSHOT_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' SELENIUM_DRIVER_LOG_DIR='/home/jenkins/workspace/****-e2e-tests-pr/log' pytest /home/jenkins/workspace/****-e2e-tests-pr/regression/tests -v --junit-xml='/home/jenkins/workspace/****-e2e-tests-pr/reports/e2e_tests_results.xml' --exclude=whitelabel\|enterprise
> ```
@feanil I've updated the PR, please let me know if any further change is required as jenkins is not triggered when I create/update the PR

**Comment by ziafazal** [comment]
@emzubair you can run jenkins test command in your devstack e2e container like this
`./jenkins/end_to_end_tests.sh`

**Comment by ziafazal** [comment]
jenkins run e2e

**Comment by feanil** [comment]
jenkins run e2e

**Comment by feanil** [comment]
Looks like this fails now that I have actually removed the files from edx-platform.  Can you rebase this PR of the latest master of e2e so that we can confirm everything is working before I merge.

**Comment by emzubair** [comment]
> Looks like this fails now that I have actually removed the files from edx-platform. Can you rebase this PR of the latest master of e2e so that we can confirm everything is working before I merge.

@feanil I've rebased & updated PR.

**Comment by feanil** [comment]
jenkins run e2e

**Pull request merged**
