### PR TITLE
[BD-18] Copied pages from edx-platform and removed pages app

### PR DESCRIPTION
**Pull request by ziafazal**
Copied pages from edx-platform and removed pages app.
Changes to run tests on devstack.
Updated end date of sample course so it would not fall in archived courses.

### CODE REVIEW

**Comment by ziafazal** [comment]
@feanil could you please review this one?

**Comment by feanil** [comment]
jenkins run all

**Comment by feanil** [comment]
running again with a clean venv

jenkins run all

**Comment by feanil** [comment]
the microsites failure can be ignored, the tests were supposed to be turned off but weren't

**Pull request merged**
