### PR TITLE
Remove flaky test_studio_footer_links test.

### PR DESCRIPTION
**Pull request by attiyaIshaque**
### [EDUCATOR-2519](https://openedx.atlassian.net/browse/EDUCATOR-2519)

Removing flaky e2e test.

### CODE REVIEW

**Comment by attiyaIshaque** [comment]
jenkins run e2e

**Comment by attiyaIshaque** [comment]
@efischer19 @scottrish @Rabia23 Can you guys please review?

**Comment by Rabia23** [comment]
👍

**Comment by feanil** [comment]
Merging so I can re-run the tests and verify there are no other issues.

**Comment by attiyaIshaque** [comment]
@feanil Thanks. Please tell when re-run is complete.

**Comment by feanil** [comment]
The run after removing this completed successfully as expected.

**Pull request merged**
