### PR TITLE
Fix for too many redirect issue

### PR DESCRIPTION
**Pull request by ziafazal**
Fix for `Firefox has detected that the server is redirecting the request for this address in a way that will never complete.`

### CODE REVIEW

**Comment by crice100** [comment]
@ziafazal Do you happen to be know why this is necessary? Did something change so that we require it now?

**Comment by ziafazal** [comment]
@crice100 I think either of these could have been changed

1. e2e test user `edx-e2e-tests@edx.org` is no more a global staff
2. domain of the session cookie on LMS side return by `user_api/v1/account/login_session` API.

**Comment by crice100** [comment]
Thanks Zia. Since we don't seem to know exactly why this change would be required and we've already merged [the revert PR](https://github.com/edx/edx-platform/pull/22413/), should we wait to see if that revert fixes the test before merging this?

**Comment by ziafazal** [comment]
@crice100 yeah I'm open to keep my changes away from stage to see if e2e tests pass without them.

**Comment by estute** [comment]
jenkins run e2e

**Comment by cpennington** [comment]
jenkins run e2e

**Pull request merged**
