### PR TITLE
bump bok-choy version to 0.7.3

### PR DESCRIPTION
**Pull request by kashifch**
bump bok-choy version to 0.7.3

### CODE REVIEW

**Comment by kashifch** [comment]
jenkins run microsites

**Comment by kashifch** [comment]
jenkins run e2e

**Comment by feanil** [comment]
jenkins run all

**Comment by estute** [comment]
jenkins run e2e

**Comment by estute** [comment]
@kashifch this pr has removed the .gitkeep file in the logs directory. Without it, the directory is empty and therefore git no longer indexes it. For the short term, please add the empty file back in. Since the directory only seems to store artifacts created at run-time, I think we should create the directory itself at run-time (but we can do that in a separate PR)

**Comment by kashifch** [comment]
@feanil @estute thanks for the help

**Pull request merged**
