### PR TITLE
Fix the vagrant-based development environment setup

### PR DESCRIPTION
**Pull request by jzoldak**
* Update documentation
* Install additional required system dependencies
* Remove attempted usage of fabric, which was already removed
* Do not install the page objects when provisioning anyhow, as this clones the entire edx-platform repo and takes a very long time (especially on a synced folder)

Note that this still installs the apt-get version of firefox, which likely (and at the time of this writing -definitely) will not work with the version of selenium and drivers that are installed.

@edx/testeng

### CODE REVIEW

**Comment by jzoldak** [comment]
To install the correct version of Firefox, once you vagrant ssh into the virtual machine:
```
sudo apt-get purge firefox
rm -rf ~/.mozilla
curl -O https://s3.amazonaws.com/vagrant.testeng.edx.org/firefox-mozilla-build_42.0-0ubuntu1_amd64.deb
sudo apt-get install gdebi-core
sudo gdebi -nq firefox-mozilla-build_42.0-0ubuntu1_amd64.deb 
```

**Comment by jzoldak** [comment]
To run against a selenium standalone docker container, e.g. https://hub.docker.com/r/selenium/standalone-firefox/:

```
export SELENIUM_BROWSER=firefox
export SELENIUM_HOST=10.0.2.2
export SELENIUM_PORT=4444
```
**Note:** see http://stackoverflow.com/questions/16244601/vagrant-reverse-port-forwarding
for why the 10.0.2.2

**Comment by jzoldak** [comment]
@Muddasser @raeeschachar 
Does this look good to you for merging?

**Comment by raeeschachar** [comment]
yup 👍

**Pull request merged**
