### PR TITLE
test grade range fix

### PR DESCRIPTION
**Pull request by raeeschachar**

### CODE REVIEW

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
@benpatterson @jzoldak @Muddasser 
Please review. https://screencast.com/t/74sC4amUKwwp
There were a couple of issues:
1- After saving confirmation, ajax call wasn't completed (checked manually) and test was moving to the next page. 
2- browser.refresh() wasn't waiting for the page to load, used page.visit() instead.

**Comment by jzoldak** [comment]
In looking at this test and methods, the GradingPageExtended seems like isn't just extensions to the page object defined in the edx-platform, but rather it's pretty much what should live over in the original repo. I put in a ticket (LT-54) for that.

**Comment by jzoldak** [comment]
This looks good to merge. 👍

**Comment by Muddasser** [comment]
@raeeschachar 👍

**Pull request merged**
