### PR TITLE
Adding flaky decorator

### PR DESCRIPTION
**Pull request by raeeschachar**

### CODE REVIEW

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by raeeschachar** [comment]
jenkins run e2e

**Comment by benpatterson** [comment]
Just want to point out that we can see that the `@flaky` decorator was applied when we look at the flaky test report on the console log for the build:

```
14:32:08 ===Flaky Test Report===
14:32:08 
14:32:08 test_cancel_upload passed 1 out of the required 1 times. Success!
14:32:08 test_logout passed 1 out of the required 1 times. Success!
14:32:08 
14:32:08 ===End Flaky Test Report===
```

**Comment by raeeschachar** [comment]
@edx/testeng 
Need one more review/approval.

**Comment by raeeschachar** [comment]
@benpatterson 
Added one more test that was flaky on e2e master, please go through one more time.

**Comment by benpatterson** [comment]
:+1:

**Pull request merged**
